spring.application.name= api-gateway-new

server.port=9090

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.hostname=localhost
eureka.instance.instance-id=${spring.application.name}:${server.port}
eureka.instance.prefer-ip-address=false


# 1. FOOD SERVICE (ADMIN)
spring.cloud.gateway.routes[0].id=food-service
spring.cloud.gateway.routes[0].uri=lb://FOOD-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/admin/**

# 2. USER SERVICE
spring.cloud.gateway.routes[1].id=user-service
spring.cloud.gateway.routes[1].uri=lb://USER-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/users/**

# 3. ORDER SERVICE
spring.cloud.gateway.routes[2].id=order-service
spring.cloud.gateway.routes[2].uri=lb://ORDER-SERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/orders/**